### ISSUE TITLE
Feature request: STAR 

### ISSUE THREAD

**Issue by colindaven** [bioinformatics-centre/bayesembler#6]
Dear all,

I know this is on the website and is being done but I'd like to say STAR support is the most critical of the listed planned features for me.
STAR really provides huge practical advantages over Tophat in terms of speed and according to my tests accuracy especially with it's two pass alignment mode. 

Thanks,
Colin

**Comment by lassemaretty** [comment]
Hi Colin, 

Thank you for posting. We are almost done with the update containing an output prefix option and we will try to include STAR support in this release as well. We'll keep you posted.

/Lasse

**Comment by lassemaretty** [comment]
Hi Colin, 

We have looked into whether it would be possible to include STAR support in the next minor release, however it turns out that the tool we use for constructing splice-graphs does not work with STAR. The next major release, which is currently in the testing phase, will provide STAR support as it relies on our own graph construction routine.

- Lasse
